#!/bin/sh

# setup python
PYTHON=ipython

# obtain the script home
SCRIPT_HOME=$(dirname $(readlink -f $0))

# setup python path for the scripts
export PYTHONPATH=$SCRIPT_HOME:$PYTHONPATH

# call the python script
$PYTHON -i $SCRIPT_HOME/maple/run.py

